<?php

namespace djepo\PrestationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * locationPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class locationPrestationRepository extends EntityRepository
{
}
