no:
    pattern:  /
    defaults: { _controller: "djepoLocationBundle:etatDesLieux:index" }

no_show:
    pattern:  /{id}/show
    defaults: { _controller: "djepoLocationBundle:etatDesLieux:show" }

no_new:
    pattern:  /new
    defaults: { _controller: "djepoLocationBundle:etatDesLieux:new" }

no_create:
    pattern:  /create
    defaults: { _controller: "djepoLocationBundle:etatDesLieux:create" }
    requirements: { _method: post }

no_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "djepoLocationBundle:etatDesLieux:edit" }

no_update:
    pattern:  /{id}/update
    defaults: { _controller: "djepoLocationBundle:etatDesLieux:update" }
    requirements: { _method: post|put }

no_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "djepoLocationBundle:etatDesLieux:delete" }
    requirements: { _method: post|delete }
