no:
    pattern:  /
    defaults: { _controller: "djepoLocationBundle:evaluation:index" }

no_show:
    pattern:  /{id}/show
    defaults: { _controller: "djepoLocationBundle:evaluation:show" }

no_new:
    pattern:  /new
    defaults: { _controller: "djepoLocationBundle:evaluation:new" }

no_create:
    pattern:  /create
    defaults: { _controller: "djepoLocationBundle:evaluation:create" }
    requirements: { _method: post }

no_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "djepoLocationBundle:evaluation:edit" }

no_update:
    pattern:  /{id}/update
    defaults: { _controller: "djepoLocationBundle:evaluation:update" }
    requirements: { _method: post|put }

no_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "djepoLocationBundle:evaluation:delete" }
    requirements: { _method: post|delete }
