<?php

namespace djepo\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends EntityRepository
{
	
	public function getVerifierAdresse($id,$user)
	{
	
	}
}