<?php

namespace djepo\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * loyerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reglementRepository extends EntityRepository
{
}
