parameters:
#    djepo_location.example.class: djepo\LocationBundle\Example

services:
#    djepo_location.example:
#        class: %djepo_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
