<?php

namespace djepo\LocationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * evaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class evaluationRepository extends EntityRepository
{
}
