<?php

namespace djepo\LocationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * loca_logementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class loca_logementRepository extends EntityRepository
{
}
