<?php

namespace djepo\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotsCleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotsCleRepository extends EntityRepository
{
}