parameters:
#    djepo_prestation.example.class: djepo\PrestationBundle\Example

services:
#    djepo_prestation.example:
#        class: %djepo_prestation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
