ville:
    pattern:  /
    defaults: { _controller: "djepoUserBundle:Ville:index" }

ville_show:
    pattern:  /{id}/show
    defaults: { _controller: "djepoUserBundle:Ville:show" }

ville_new:
    pattern:  /new
    defaults: { _controller: "djepoUserBundle:Ville:new" }

ville_create:
    pattern:  /create
    defaults: { _controller: "djepoUserBundle:Ville:create" }
    requirements: { _method: post }

ville_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "djepoUserBundle:Ville:edit" }

ville_update:
    pattern:  /{id}/update
    defaults: { _controller: "djepoUserBundle:Ville:update" }
    requirements: { _method: post|put }

ville_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "djepoUserBundle:Ville:delete" }
    requirements: { _method: post|delete }
