# src/djepo/user/Resources/config/routing.yml
        
djepoUser_profile:
    pattern:  /espace-client
    defaults: { _controller: djepoUserBundle:Admin:index , format: html }
    requirements:
        format: html
        _method:  GET 
        
        
djepoUser_changeMail:
    pattern:  /espace-client/modifierMail
    defaults: { _controller: djepoUserBundle:Admin:modifierMail , format: html }
    requirements:
        format: html
        
djepoUser_delete:
    pattern:  /espace-client/modifierMail
    defaults: { _controller: djepoUserBundle:Admin:modifierMail , format: html }
    requirements:
        format: html
        
fos_user_inscription_register:
    pattern:   /inscription
    defaults: { _controller: FOSUserBundle:Registration:register }
    
fos_user_connexion:
    pattern:   /connexion
    defaults: { _controller: FOSUserBundle:Security:login }

#fos_user_logout:
#    pattern:   /logout
#    defaults: { _controller: FOSUserBundle:Security:logout }
    
   
    
djepoUserBundle_adresse:
    resource: "routing/adresse.yml"
    prefix:   /espace-client/adresse

djepoUserBundle_ville:
    resource: "routing/ville.yml"
    prefix:   /espace-client/ville
    
djepoUserBundle_user:
        resource: "routing/user.yml"
        prefix:   /espace-client/user   
